name: Build and Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name:  ğŸ›ï¸ Checkout
        uses: actions/checkout@v2.3.1

      - name: â„ï¸ Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: âš¡ï¸ Install
        run: yarn install

      - name: ğŸ”§ Build 
        env:
          REACT_APP_SERVICE_URL: ${{ secrets.REACT_APP_SERVICE_URL }}
          REACT_APP_RPC_URL_1: ${{ secrets.REACT_APP_RPC_URL_1 }}
          REACT_APP_RPC_URL_4: ${{ secrets.REACT_APP_RPC_URL_4 }}
          NODE_ENV: production
        run: yarn build

      - name: ğŸ’¾ Create artifact
        run: tar -zcvf build.tar.gz build/

      - name: ğŸ“¦ Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nft-marketplace-build
          path: build.tar.gz
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: success() && github.ref == 'refs/heads/master'
    steps: 
      - name:  ğŸ›ï¸ Checkout
        uses: actions/checkout@v2.3.1

      - name: ğŸ“¥ Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: nft-marketplace-build

      - name: ğŸ”¥ Unpack artifact 
        run: tar -zxvf build.tar.gz

      - name: ğŸš€ Deploy 
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages 
          folder: build 
