name: Build and Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name:  üõéÔ∏è Checkout
        uses: actions/checkout@v2.3.1

      - name: ‚ö°Ô∏è Install
        run: yarn install

      - name: üîß Build 
        env:
          REACT_APP_SERVICE_URL: ${{ secrets.REACT_APP_SERVICE_URL }}
          REACT_APP_RPC_URL_1: ${{ secrets.REACT_APP_RPC_URL_1 }}
          REACT_APP_RPC_URL_4: ${{ secrets.REACT_APP_RPC_URL_4 }}
        run: SKIP_PREFLIGHT_CHECK=true yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nft-marketplace-build
          path: build
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: success() && github.ref == 'refs/heads/master'
    steps: 
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: nft-marketplace-build
      - name: üöÄ Deploy 
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages 
          folder: build 
