name: Build and Deploy
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name:  ğŸ›ï¸ Checkout
        uses: actions/checkout@v2.3.1

      - name: âš¡ï¸ Install
        run: yarn install

      - name: ğŸ”§ Install and Build 
        env:
          REACT_APP_SERVICE_URL: ${{ secrets.REACT_APP_SERVICE_URL }}
          REACT_APP_RPC_URL_1: ${{ secrets.REACT_APP_RPC_URL_1 }}
          REACT_APP_RPC_URL_4: ${{ secrets.REACT_APP_RPC_URL_4 }}
        run: SKIP_PREFLIGHT_CHECK=true yarn build

      - name: ğŸš€ Deploy 
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages 
          folder: build 